spring:
  datasource:
    url: ${dbUrl}
    username: ${dbUser}
    password: ${dbPassword}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    validate-on-migrate: true
    clean-disabled: false
  mail:
    host: smtp.gmail.com
    username: ${mailUser}
    password: ${mailPass}
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  debug: false
jwt:
  token:
    secret: ${token}
    expired: 3600000