### GET CATEGORIES BY PARENT ID
GET http://localhost:8080/api/categories/child?id=2
Accept: application/json

### GET CATEGORY BY ID
GET http://localhost:8080/api/categories/12
Accept: application/json

### CREATE CATEGORY
POST http://localhost:8080/api/admin/categories/create
Content-Type: application/json

{
  "name": "mini car",
  "parentId": 2
}

### GET ALL CATEGORIES
GET http://localhost:8080/api/categories

###  RENAME CATEGORY
PUT http://localhost:8080/api/admin/categories/2?name=car
Accept: application/json
